### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [kcarullo/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report: 
* _Score Level:_ 4/4
* _Comment(s):_ Conclusions are clear and are supported by SQL evidence in all answers. 
 
### Criteria 2: Query Accuracy
* _Score Level:_ 4/4
* _Comment(s):_ : Each query produces the correct output
 
### Criteria 3: Query Formatting
* _Score Level:_ 4/4
* _Comment(s):_ Best practices were used and the code was formatted accurately. 
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4/4
* _Comment(s):_ The outputs given for each analysis done was elaborate and exceeded expectations.

 ### Overall Score: 16/16

**Comment by kcarullo** [comment]
Thank you for the review.
